sonar.projectKey=bless-booking-api
sonar.working.directory=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service
sonar.pullrequest.cache.basepath=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service
sonar.sources=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.vs\\VSWorkspaceState.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.vs\\Bless.Booking.Service\\config\\applicationhost.config",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.vs\\Bless.Booking.Service\\v17\\DocumentLayout.backup.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.vs\\Bless.Booking.Service\\v17\\DocumentLayout.json"

BD3DBA98-695F-4B9D-A61D-58EAFAA3AAA3.sonar.projectKey=bless-booking-api:BD3DBA98-695F-4B9D-A61D-58EAFAA3AAA3
BD3DBA98-695F-4B9D-A61D-58EAFAA3AAA3.sonar.projectName=Bless.Models
BD3DBA98-695F-4B9D-A61D-58EAFAA3AAA3.sonar.projectBaseDir=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models
BD3DBA98-695F-4B9D-A61D-58EAFAA3AAA3.sonar.sourceEncoding=utf-8
BD3DBA98-695F-4B9D-A61D-58EAFAA3AAA3.sonar.tests=
BD3DBA98-695F-4B9D-A61D-58EAFAA3AAA3.sonar.sources=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\Barbero.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\HorarioDisponible.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\LoginRequest.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\LoginResponse.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\Reserva.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\ReservaRequest.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\Response.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\Review.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\Servicio.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\Usuario.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\obj\\Bless.Models.csproj.nuget.dgspec.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\obj\\project.assets.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\bin\\Debug\\net8.0\\Bless.Models.deps.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Models\\obj\\Debug\\net8.0\\Bless.Models.sourcelink.json"

BD3DBA98-695F-4B9D-A61D-58EAFAA3AAA3.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\0"
BD3DBA98-695F-4B9D-A61D-58EAFAA3AAA3.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\0\\Issues.json"
BD3DBA98-695F-4B9D-A61D-58EAFAA3AAA3.sonar.cs.scanner.telemetry=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\0\\Telemetry.json"

BD3DBA98-695F-4B9D-A61D-58EAFAA3AAA3.sonar.working.directory=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\.sonar\\mod0
679373D7-3418-4314-BBC8-2D0BEF1D5D41.sonar.projectKey=bless-booking-api:679373D7-3418-4314-BBC8-2D0BEF1D5D41
679373D7-3418-4314-BBC8-2D0BEF1D5D41.sonar.projectName=Bless.BusinessLogic.Interfaces
679373D7-3418-4314-BBC8-2D0BEF1D5D41.sonar.projectBaseDir=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic.Interfaces
679373D7-3418-4314-BBC8-2D0BEF1D5D41.sonar.sourceEncoding=utf-8
679373D7-3418-4314-BBC8-2D0BEF1D5D41.sonar.tests=
679373D7-3418-4314-BBC8-2D0BEF1D5D41.sonar.sources=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic.Interfaces\\obj\\Bless.BusinessLogic.Interfaces.csproj.nuget.dgspec.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic.Interfaces\\obj\\project.assets.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic.Interfaces\\bin\\Debug\\net8.0\\Bless.BusinessLogic.Interfaces.deps.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic.Interfaces\\obj\\Debug\\net8.0\\Bless.BusinessLogic.Interfaces.sourcelink.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic.Interfaces\\IBarbero.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic.Interfaces\\IReserva.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic.Interfaces\\IServicio.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic.Interfaces\\IUsuario.cs"

679373D7-3418-4314-BBC8-2D0BEF1D5D41.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\1"
679373D7-3418-4314-BBC8-2D0BEF1D5D41.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\1\\Issues.json"
679373D7-3418-4314-BBC8-2D0BEF1D5D41.sonar.cs.scanner.telemetry=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\1\\Telemetry.json"

679373D7-3418-4314-BBC8-2D0BEF1D5D41.sonar.working.directory=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\.sonar\\mod1
512EAFF7-7DAF-46E4-943E-BB15B52E7BC8.sonar.projectKey=bless-booking-api:512EAFF7-7DAF-46E4-943E-BB15B52E7BC8
512EAFF7-7DAF-46E4-943E-BB15B52E7BC8.sonar.projectName=Bless.DataAccess.Interfaces
512EAFF7-7DAF-46E4-943E-BB15B52E7BC8.sonar.projectBaseDir=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess.Interfaces
512EAFF7-7DAF-46E4-943E-BB15B52E7BC8.sonar.sourceEncoding=utf-8
512EAFF7-7DAF-46E4-943E-BB15B52E7BC8.sonar.tests=
512EAFF7-7DAF-46E4-943E-BB15B52E7BC8.sonar.sources=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess.Interfaces\\obj\\Bless.DataAccess.Interfaces.csproj.nuget.dgspec.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess.Interfaces\\obj\\project.assets.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess.Interfaces\\bin\\Debug\\net8.0\\Bless.DataAccess.Interfaces.deps.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess.Interfaces\\obj\\Debug\\net8.0\\Bless.DataAccess.Interfaces.sourcelink.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess.Interfaces\\IBarbero.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess.Interfaces\\IConnectionManager.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess.Interfaces\\IReserva.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess.Interfaces\\IServicio.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess.Interfaces\\IUsuario.cs"

512EAFF7-7DAF-46E4-943E-BB15B52E7BC8.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\2"
512EAFF7-7DAF-46E4-943E-BB15B52E7BC8.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\2\\Issues.json"
512EAFF7-7DAF-46E4-943E-BB15B52E7BC8.sonar.cs.scanner.telemetry=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\2\\Telemetry.json"

512EAFF7-7DAF-46E4-943E-BB15B52E7BC8.sonar.working.directory=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\.sonar\\mod2
13D227BF-87A6-45CD-BEF3-D6C05B1A83C8.sonar.projectKey=bless-booking-api:13D227BF-87A6-45CD-BEF3-D6C05B1A83C8
13D227BF-87A6-45CD-BEF3-D6C05B1A83C8.sonar.projectName=Bless.DataAccess
13D227BF-87A6-45CD-BEF3-D6C05B1A83C8.sonar.projectBaseDir=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess
13D227BF-87A6-45CD-BEF3-D6C05B1A83C8.sonar.sourceEncoding=utf-8
13D227BF-87A6-45CD-BEF3-D6C05B1A83C8.sonar.tests=
13D227BF-87A6-45CD-BEF3-D6C05B1A83C8.sonar.sources=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess\\obj\\Bless.DataAccess.csproj.nuget.dgspec.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess\\obj\\project.assets.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess\\bin\\Debug\\net8.0\\Bless.DataAccess.deps.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess\\obj\\Debug\\net8.0\\Bless.DataAccess.sourcelink.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess\\Barbero.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess\\ConnectionManager.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess\\Reserva.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess\\Servicio.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.DataAccess\\Usuario.cs"

13D227BF-87A6-45CD-BEF3-D6C05B1A83C8.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\3"
13D227BF-87A6-45CD-BEF3-D6C05B1A83C8.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\3\\Issues.json"
13D227BF-87A6-45CD-BEF3-D6C05B1A83C8.sonar.cs.scanner.telemetry=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\3\\Telemetry.json"

13D227BF-87A6-45CD-BEF3-D6C05B1A83C8.sonar.working.directory=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\.sonar\\mod3
5914A5B1-34ED-4A44-8FB9-2ABCF5150A16.sonar.projectKey=bless-booking-api:5914A5B1-34ED-4A44-8FB9-2ABCF5150A16
5914A5B1-34ED-4A44-8FB9-2ABCF5150A16.sonar.projectName=Bless.BusinessLogic
5914A5B1-34ED-4A44-8FB9-2ABCF5150A16.sonar.projectBaseDir=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic
5914A5B1-34ED-4A44-8FB9-2ABCF5150A16.sonar.sourceEncoding=utf-8
5914A5B1-34ED-4A44-8FB9-2ABCF5150A16.sonar.tests=
5914A5B1-34ED-4A44-8FB9-2ABCF5150A16.sonar.sources=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic\\obj\\Bless.BusinessLogic.csproj.nuget.dgspec.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic\\obj\\project.assets.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic\\bin\\Debug\\net8.0\\Bless.BusinessLogic.deps.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic\\obj\\Debug\\net8.0\\Bless.BusinessLogic.sourcelink.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic\\Barbero.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic\\NotificacionHub.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic\\NotificacionService.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic\\Reserva.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic\\Servicio.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.BusinessLogic\\Usuario.cs"

5914A5B1-34ED-4A44-8FB9-2ABCF5150A16.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\4"
5914A5B1-34ED-4A44-8FB9-2ABCF5150A16.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\4\\Issues.json"
5914A5B1-34ED-4A44-8FB9-2ABCF5150A16.sonar.cs.scanner.telemetry=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\4\\Telemetry.json"

5914A5B1-34ED-4A44-8FB9-2ABCF5150A16.sonar.working.directory=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\.sonar\\mod4
B3797067-2E34-42DA-9C65-A325088B585B.sonar.projectKey=bless-booking-api:B3797067-2E34-42DA-9C65-A325088B585B
B3797067-2E34-42DA-9C65-A325088B585B.sonar.projectName=Bless.Booking.Service
B3797067-2E34-42DA-9C65-A325088B585B.sonar.projectBaseDir=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service
B3797067-2E34-42DA-9C65-A325088B585B.sonar.sourceEncoding=utf-8
B3797067-2E34-42DA-9C65-A325088B585B.sonar.tests=
B3797067-2E34-42DA-9C65-A325088B585B.sonar.sources=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\appsettings.Development.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\appsettings.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\services.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\obj\\Bless.Booking.Service.csproj.nuget.dgspec.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\obj\\project.assets.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\Properties\\launchSettings.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\bin\\Debug\\net8.0\\Bless.Booking.Service.deps.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\bin\\Debug\\net8.0\\Bless.Booking.Service.runtimeconfig.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\bin\\Debug\\net8.0\\Bless.Booking.Service.staticwebassets.endpoints.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\bin\\Debug\\net8.0\\services.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\obj\\Debug\\net8.0\\ApiEndpoints.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\obj\\Debug\\net8.0\\Bless.Booking.Service.sourcelink.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\obj\\Debug\\net8.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\obj\\Debug\\net8.0\\staticwebassets.build.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\obj\\Debug\\net8.0\\EndpointInfo\\Bless.Booking.Service.json",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\Controllers\\AuthController.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\Controllers\\BarberoController.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\Controllers\\GooglePlacesController.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\Controllers\\NotificacionesController.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\Controllers\\PushController.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\Controllers\\ReservaController.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\Controllers\\ServicioController.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\GooglePlacesService.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\Program.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\obj\\Debug\\net8.0\\Bless.Booking.Service.GlobalUsings.g.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\obj\\Debug\\net8.0\\Bless.Booking.Service.AssemblyInfo.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\obj\\Debug\\net8.0\\Bless.Booking.Service.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\Bless.Booking.Service\\Bless.Booking.Service.http"

B3797067-2E34-42DA-9C65-A325088B585B.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\5"
B3797067-2E34-42DA-9C65-A325088B585B.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\5\\Issues.json"
B3797067-2E34-42DA-9C65-A325088B585B.sonar.cs.scanner.telemetry=\
"C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\5\\Telemetry.json"

B3797067-2E34-42DA-9C65-A325088B585B.sonar.working.directory=C:\\Users\\Cristopher Avendano\\source\\repos\\Bless.Booking.Service\\.sonarqube\\out\\.sonar\\mod5
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=BD3DBA98-695F-4B9D-A61D-58EAFAA3AAA3,679373D7-3418-4314-BBC8-2D0BEF1D5D41,512EAFF7-7DAF-46E4-943E-BB15B52E7BC8,13D227BF-87A6-45CD-BEF3-D6C05B1A83C8,5914A5B1-34ED-4A44-8FB9-2ABCF5150A16,B3797067-2E34-42DA-9C65-A325088B585B

